spring:
  application:
    name: tkk

  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB

  config:
    import: optional:application-api.yml

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/tkk?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: tkk
    password: kosmo1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: llama3.2:3b

server:
  port: 8080

naver:
  search:
    client-id: ${keys.naver.search.client-id}
    client-secret: ${keys.naver.search.client-secret}

  key-id: ${keys.naver.key-id}
  key: ${keys.naver.key}

openai:
  api-key: ${keys.openai.api-key}

file:
  upload-dir: ./uploads

cloud:
  aws:
    credentials:
      access-key: ${aws.access-key}
      secret-key: ${aws.secret-key}
    s3:
      bucket: ${aws.s3-bucket}
    region:
      static: ap-northeast-2
    stack:
      auto: false

keys:
  naver:
    search:
      client-id: your-real-naver-search-client-id
      client-secret: your-real-naver-search-client-secret
    key-id: your-real-naver-key-id
    key: your-real-naver-key

  openai:
    api-key: your-real-openai-api-key

aws:
  access-key: your-aws-access-key
  secret-key: your-aws-secret-key
  s3-bucket: tkuku-bucket