spring:
  config:
    activate:
      on-profile: deploy

  datasource:
    # ğŸ”¥ Docker Oracle XEê°€ host 3000 í¬íŠ¸ë¡œ ì—´ë ¤ìˆë˜ ì˜ˆì „ ì„¤ì •ìœ¼ë¡œ ë³µê·€
    url: jdbc:mysql://thekuku.czmmuc4g8era.ap-northeast-2.rds.amazonaws.com:3306/tkk
    username: thekuku
    password: thekukupw
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 80
