# src/main/resources/application.yaml

spring:
  application:
    name: tkk

  config:
    import: optional:application-api.yaml   # ğŸ”¹ api íŒŒì¼ ë¶ˆëŸ¬ì˜¤ê¸° (í™•ì¥ì .yaml ì£¼ì˜)

  datasource:
#    url: jdbc:oracle:thin:@//localhost:3000/XEPDB1
    url: jdbc:oracle:thin:@//localhost:1521/XEPDB1
    username: tkk
    password: kosmo1234
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect

server:
  port: 8080
