spring:
  application:
    name: tkk

  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB

  config:
    import: optional:application-api.yml   # ğŸ”¥ ì—¬ê¸° ì£¼ì˜: .yml ë¡œ í†µì¼

  datasource:
    url: jdbc:mysql://localhost:3307/tkk
    username: tkk
    password: kosmo1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: llama3.2:3b

server:
  port: 8080

naver:
  search:
    client-id: ${keys.naver.search.client-id}
    client-secret: ${keys.naver.search.client-secret}

  key-id: ${keys.naver.key-id}
  key: ${keys.naver.key}

openai:
  api-key: ${keys.openai.api-key}

file:
  upload-dir: ./uploads

cloud:
  aws:
    credentials:
      # ğŸ”¹ í™˜ê²½ë³€ìˆ˜ ë§ê³ , ìš°ë¦¬ê°€ ë”°ë¡œ ì •ì˜í•œ aws.* í‚¤ ì°¸ì¡°
      access-key: ${aws.access-key}
      secret-key: ${aws.secret-key}
    s3:
      bucket: ${aws.s3-bucket}
    region:
      static: ap-northeast-2
    stack:
      auto: false