spring:
  application:
    name: tkk
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/XEPDB1
    username: tkk
    password: kosmo1234
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
server:
  port: 8080

naver:
  key-id: 8ehod4l0bq
  key: ${NAVER_CLIENT_SECRET}
